
@startmindmap OSOS

title Open source for Official statistics

+ OSOS
-- <b>Why</b>
--- Transparency
--- User needs
---- Reproducible
---- Comparable
--- Sharing
---- Cut Costs
'---- Increase quality
'---- Competence
++ <b>What</b>
+++ Apps
+++ Methods
+++ Study/Research
++ <b>How</b>
+++ Culture
++++ Community building MGMT
++++ Arhcitectural Engineering principles
+++++ R
+++++ Python
++++ Security
+++ Capabilities
+++ Use cases
+++ Sponsorship
++++ Resources
++++ Funding

@endmindmap
