@startuml
' Relais application architecture
'
' Using:
' - https://github.com/rabelenda/cicon-plantuml-sprites/blob/master/sprites-list.md for icons
' - http://plantuml.com/en/creole for formatting

!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/tomcat.puml
!includeurl SPRITESURL/postgresql.puml
!includeurl SPRITESURL/java.puml
!includeurl SPRITESURL/mysql.puml

title __**Relais architecture**__

' Users ----------
:User:

' Nodes ----------
node "Workbench \n <$tomcat> <$java>" as WB {

}

node "Batch \n <$java>" as BATCH {
    package Engines AS ENGINES {
        [Java engine] as JAVA_ENGINE
        [R engine] as R_ENGINE
    }
    package Runtimes as RUNTIMES {
        [Java runtime] as JAVA_RUNTIME
        [R runtime]
    }
}

' Databases ----------
database "Relais Data \n <$mysql>" as DATA_DB {

}

database "Relais Metadata \n <$mysql>" as METADATA_DB {

}

' Links ----------
User -down-> WB

WB <-down-> DATA_DB
WB <-down-> METADATA_DB
WB -> BATCH

JAVA_ENGINE -down-> JAVA_RUNTIME: invoke

JAVA_ENGINE <-> DATA_DB
JAVA_ENGINE <-> METADATA_DB

' Notes --------
note left of User: User execute a business function


@enduml